name: Build LaTeX Resume - Manual

on:
   - workflow_dispatch
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Tag the latest release
        run: |
          git push --delete origin latest
          git push
          git tag -f latest ${{ github.sha }}
          git push origin -f latest
